import { NextResponse, NextRequest } from 'next/server';
import fs from 'fs';
import path from 'path';
import { distributionsCache, CACHE_TTL, HTTP_CACHE_MAX_AGE, cachedQuery } from '@/lib/cache';

const DISTRIBUTIONS_DIR = process.env.DIST_DIR || '/data/ECOD0/html/distributions';
const BASE_URL = 'http://prodata.swmed.edu/ecod/distributions';

// Generated by scripts/build_releases_index.py after each release. Reading one
// manifest replaces stat()-ing ~2,400 files over NFS on every cache miss, and it
// is the same document published for scripted consumers, so the page and the API
// cannot drift apart. If it is missing the page shows no releases rather than
// walking the tree on a request path.
const INDEX_FILE = 'releases-full.json';

interface FileInfo {
  name: string;
  size: number;
  sizeFormatted: string;
  url: string;
  modified: string;
  md5?: string;
  description?: string;
}

interface VersionFiles {
  main: FileInfo[];       // classification tables and sequences
  f40: FileInfo[];
  f70: FileInfo[];
  f99: FileInfo[];
  blast: FileInfo[];      // domain BLAST database (sequence search)
  chainwise: FileInfo[];  // chain BLAST database
  foldseek: FileInfo[];   // Foldseek database (structure search): archive first, then unpacked files
  hhsuite: FileInfo[];    // HH-suite profile database
  other: FileInfo[];
}

interface VersionInfo {
  version: string;
  date: string;
  releaseNotes?: string;
  // Zenodo DOI of the archived copy of this release, where one exists.
  archiveDoi?: string;
  // Members not rebuilt for this release, listed from the release they were
  // built for: { hhsuite: 'v295' }.
  carriedFrom?: Partial<Record<keyof VersionFiles, string>>;
  files: VersionFiles;
}

interface VersionSummary {
  version: string;
  date: string;
  fileCount: number;
  totalBytes: number;
  totalFormatted: string;
  naming: 'develop' | 'v';
}

interface DistributionData {
  currentVersion: VersionInfo | null;
  previousVersions: VersionSummary[];
  archive: {
    releaseCount: number;
    first: string | null;
    last: string | null;
    namingNote: string;
    indexUrl: string;
  } | null;
}

/* ---------------------------------------------------------------- helpers */

function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
}

function getReleaseNotes(version: string): string | undefined {
  const variants = [
    `RELEASE_NOTES_${version.toUpperCase().replace(/\./g, '_')}.md`,
    `RELEASE_NOTES_${version.toUpperCase()}.md`,
  ];
  for (const filename of variants) {
    try {
      return fs.readFileSync(path.join(DISTRIBUTIONS_DIR, filename), 'utf-8');
    } catch {
      continue;
    }
  }
  return undefined;
}

/* ------------------------------------------------------------- the index */

interface IndexFile {
  name: string;
  size: number;
  modified: string;
  kind: string;
  description: string;
  representative_set?: string;
  md5?: string;
}

interface IndexRelease {
  release: string;
  label: string;
  naming: 'develop' | 'v';
  date: string;
  current: boolean;
  file_count: number;
  total_bytes: number;
  files: IndexFile[];
}

interface IndexDoc {
  generated: string;
  current_release: string | null;
  release_count: number;
  span: { first: string; last: string } | null;
  naming_note: string;
  releases: IndexRelease[];
}

function loadIndex(): IndexDoc | null {
  try {
    const raw = fs.readFileSync(path.join(DISTRIBUTIONS_DIR, INDEX_FILE), 'utf-8');
    const doc = JSON.parse(raw) as IndexDoc;
    return Array.isArray(doc.releases) && doc.releases.length ? doc : null;
  } catch {
    return null;
  }
}

function toFileInfo(f: IndexFile): FileInfo {
  return {
    name: f.name,
    size: f.size,
    sizeFormatted: formatFileSize(f.size),
    url: `${BASE_URL}/${f.name}`,
    modified: f.modified,
    ...(f.md5 ? { md5: f.md5 } : {}),
    ...(f.description ? { description: f.description } : {}),
  };
}

// Archived copies of releases on Zenodo (version DOIs).
const ZENODO_DOI: Record<string, string> = {
  'v295.2': '10.5281/zenodo.23041269',
};

// Members that are not rebuilt with every release. If the current release has
// none, the page lists the most recent release's copy and says which it is.
const CARRY_FORWARD: { bucket: keyof VersionFiles; kind: string }[] = [
  { bucket: 'hhsuite', kind: 'hhsuite_db' },
];

const MAIN_KINDS = new Set([
  'domains', 'names', 'sequences', 'hierarchy', 'checksums', 'pfam_map', 'chainwise',
]);

// The index records what a file *is*; the page groups by where it belongs on
// screen. The search databases come first: a reader looking for the Foldseek or
// HH-suite database wants it with the other search databases, even though both
// are built from the F40 set. After that, representative-set membership wins over
// kind, because a reader looking for F40 wants every F40 file together.
function groupFiles(files: IndexFile[]): VersionFiles {
  const out: VersionFiles = {
    main: [], f40: [], f70: [], f99: [], blast: [], chainwise: [], foldseek: [], hhsuite: [], other: [],
  };
  for (const f of files) {
    const info = toFileInfo(f);
    if (f.kind === 'foldseek_db') out.foldseek.push(info);
    else if (f.kind === 'hhsuite_db') out.hhsuite.push(info);
    else if (f.representative_set === 'F40') out.f40.push(info);
    else if (f.representative_set === 'F70') out.f70.push(info);
    else if (f.representative_set === 'F99') out.f99.push(info);
    else if (f.kind === 'blast_db') out.blast.push(info);
    // The chain sequences belong with the other sequences; the rest of the
    // chainwise files are its BLAST database.
    else if (f.kind === 'chainwise') (f.name.endsWith('.fa') ? out.main : out.chainwise).push(info);
    else if (MAIN_KINDS.has(f.kind)) out.main.push(info);
    else out.other.push(info);
  }
  for (const k of Object.keys(out) as (keyof VersionFiles)[]) {
    out[k].sort((a, b) => a.name.localeCompare(b.name));
  }
  // Archives before the unpacked files they contain.
  for (const k of ['foldseek', 'hhsuite'] as const) {
    out[k].sort((a, b) => Number(b.name.endsWith('.tar.gz')) - Number(a.name.endsWith('.tar.gz')));
  }
  return out;
}

function toVersionInfo(r: IndexRelease): VersionInfo {
  return {
    version: r.release,
    date: r.date,
    releaseNotes: getReleaseNotes(r.release),
    ...(ZENODO_DOI[r.release] ? { archiveDoi: ZENODO_DOI[r.release] } : {}),
    files: groupFiles(r.files),
  };
}

function carryForward(current: VersionInfo, previous: IndexRelease[]): VersionInfo {
  for (const { bucket, kind } of CARRY_FORWARD) {
    if (current.files[bucket].length) continue;
    // The index is newest-first, so the first release with the member is the latest.
    const source = previous.find(r => r.files.some(f => f.kind === kind));
    if (!source) continue;
    current.files[bucket] = groupFiles(source.files.filter(f => f.kind === kind))[bucket];
    current.carriedFrom = { ...current.carriedFrom, [bucket]: source.release };
  }
  return current;
}

function toSummary(r: IndexRelease): VersionSummary {
  return {
    version: r.release,
    date: r.date,
    fileCount: r.file_count,
    totalBytes: r.total_bytes,
    totalFormatted: formatFileSize(r.total_bytes),
    naming: r.naming,
  };
}

/* ------------------------------------------------------------------ build */

async function buildDistributionData(): Promise<DistributionData> {
  const index = loadIndex();

  if (!index) {
    return { currentVersion: null, previousVersions: [], archive: null };
  }

  // The index is written newest-first.
  const [current, ...previous] = index.releases;

  return {
    currentVersion: current ? carryForward(toVersionInfo(current), previous) : null,
    previousVersions: previous.map(toSummary),
    archive: {
      releaseCount: index.release_count,
      first: index.span?.first ?? null,
      last: index.span?.last ?? null,
      namingNote: index.naming_note,
      indexUrl: `${BASE_URL}/releases.json`,
    },
  };
}

async function buildOneVersion(version: string): Promise<VersionInfo | null> {
  const index = loadIndex();
  if (!index) return null;
  const rel = index.releases.find(r => r.release === version);
  return rel ? toVersionInfo(rel) : null;
}

/* -------------------------------------------------------------------- GET */

export async function GET(request: NextRequest) {
  try {
    const version = request.nextUrl.searchParams.get('version');

    if (version) {
      // The version reaches the cache key, so constrain it to the shapes the
      // archive actually uses before it goes any further.
      if (!/^(v\d+(\.\d+)?|develop\d+)$/.test(version)) {
        return NextResponse.json({ error: 'Invalid version' }, { status: 400 });
      }
      const data = await cachedQuery<VersionInfo | null>(
        distributionsCache,
        `distributions:${version}`,
        CACHE_TTL.DISTRIBUTIONS,
        () => buildOneVersion(version),
      );
      if (!data) {
        return NextResponse.json({ error: 'Unknown version' }, { status: 404 });
      }
      return NextResponse.json(data, {
        headers: {
          'Cache-Control': `public, max-age=${HTTP_CACHE_MAX_AGE.DISTRIBUTIONS}, stale-while-revalidate=300`,
        },
      });
    }

    const data = await cachedQuery<DistributionData>(
      distributionsCache,
      'distributions',
      CACHE_TTL.DISTRIBUTIONS,
      buildDistributionData,
    );

    return NextResponse.json(data, {
      headers: {
        'Cache-Control': `public, max-age=${HTTP_CACHE_MAX_AGE.DISTRIBUTIONS}, stale-while-revalidate=300`,
      },
    });
  } catch (error) {
    console.error('Error reading distributions:', error);
    return NextResponse.json(
      { error: 'Failed to read distribution data' },
      { status: 500 },
    );
  }
}
